# Generated by Django 2.1.7 on 2019-02-12 08:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbox',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
