# Generated by Django 2.1.7 on 2019-02-18 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_chatbox_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connected',
            old_name='group',
            new_name='group_ID',
        ),
        migrations.RenameField(
            model_name='connected',
            old_name='message',
            new_name='message_ID',
        ),
    ]
